[package]
name = "gbenchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "gbenchmark_demo"
path = "src/bin/gbenchmark_demo/main.rs"